# Generated by Django 2.2.1 on 2019-05-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tickets_available',
            field=models.IntegerField(default=None),
        ),
    ]
