# Generated by Django 2.2.1 on 2019-05-31 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20190529_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_desc',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
