# Generated by Django 2.2.1 on 2019-05-31 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_ticket_ticket_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=None)),
                ('updated_at', models.DateTimeField(default=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='ticket',
        ),
        migrations.AddField(
            model_name='booking',
            name='total_paid',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='booking',
            name='transaction_id',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_desc',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='CartInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=None)),
                ('created_at', models.DateTimeField(default=None)),
                ('updated_at', models.DateTimeField(default=None)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Cart')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Ticket')),
            ],
        ),
        migrations.CreateModel(
            name='BookingInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=None)),
                ('created_at', models.DateTimeField(default=None)),
                ('updated_at', models.DateTimeField(default=None)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Booking')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Ticket')),
            ],
        ),
    ]
